<?php

use App\Models\Country;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('code', 2)->unique();
            $table->string('name');
            $table->string('continent', 30)->nullable();
            $table->string('continent_code', 2)->nullable();
            $table->boolean('active')->default(false);
        });

        Country::insert([
            ['id' => 1, 'code' => 'AF', 'name' => 'Afganistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 2, 'code' => 'AX', 'name' => 'Islas Aland', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 3, 'code' => 'AL', 'name' => 'Albania', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 4, 'code' => 'DZ', 'name' => 'Argelia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 5, 'code' => 'AS', 'name' => 'Samoa Americana', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 6, 'code' => 'AD', 'name' => 'Andorra', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 7, 'code' => 'AO', 'name' => 'Angola', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 8, 'code' => 'AI', 'name' => 'Anguila', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 9, 'code' => 'AQ', 'name' => 'Antártida', 'continent' => 'Antarctica', 'continent_code' => 'AN', 'active' => 0],
            ['id' => 10, 'code' => 'AG', 'name' => 'Antigua y Barbuda', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 11, 'code' => 'AR', 'name' => 'Argentina', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 12, 'code' => 'AM', 'name' => 'Armenia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 13, 'code' => 'AW', 'name' => 'Aruba', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 14, 'code' => 'AU', 'name' => 'Australia', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 1],
            ['id' => 15, 'code' => 'AT', 'name' => 'Austria', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 16, 'code' => 'AZ', 'name' => 'Azerbaiyán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 17, 'code' => 'BS', 'name' => 'Bahamas', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 18, 'code' => 'BH', 'name' => 'Baréin', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 19, 'code' => 'BD', 'name' => 'Bangladés', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 20, 'code' => 'BB', 'name' => 'Barbados', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 21, 'code' => 'BY', 'name' => 'Bielorrusia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 22, 'code' => 'BE', 'name' => 'Bélgica', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 23, 'code' => 'BZ', 'name' => 'Belice', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 24, 'code' => 'BJ', 'name' => 'Benín', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 25, 'code' => 'BM', 'name' => 'Bermudas', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 26, 'code' => 'BT', 'name' => 'Bután', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 27, 'code' => 'BO', 'name' => 'Bolivia', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 28, 'code' => 'BA', 'name' => 'Bosnia y Herzegovina', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 29, 'code' => 'BW', 'name' => 'Botsuana', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 30, 'code' => 'BV', 'name' => 'Isla Bouvet', 'continent' => 'Antarctica', 'continent_code' => 'AN', 'active' => 0],
            ['id' => 31, 'code' => 'BR', 'name' => 'Brasil', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 32, 'code' => 'IO', 'name' => 'Territorio Británico del Océano Índico', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 33, 'code' => 'BN', 'name' => 'Brunéi', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 34, 'code' => 'BG', 'name' => 'Bulgaria', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 35, 'code' => 'BF', 'name' => 'Burkina Faso', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 36, 'code' => 'BI', 'name' => 'Burundi', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 37, 'code' => 'CV', 'name' => 'Cabo Verde', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 38, 'code' => 'KH', 'name' => 'Camboya', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 39, 'code' => 'CM', 'name' => 'Camerún', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 40, 'code' => 'CA', 'name' => 'Canadá', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 41, 'code' => 'BQ', 'name' => 'Caribe neerlandés', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 42, 'code' => 'KY', 'name' => 'Islas Caimán', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 43, 'code' => 'CF', 'name' => 'República Centroafricana', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 44, 'code' => 'TD', 'name' => 'Chad', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 45, 'code' => 'CL', 'name' => 'Chile', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 46, 'code' => 'CN', 'name' => 'China', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 47, 'code' => 'CX', 'name' => 'Isla de Navidad', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 48, 'code' => 'CC', 'name' => 'Islas Cocos', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 49, 'code' => 'CO', 'name' => 'Colombia', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 50, 'code' => 'KM', 'name' => 'Comoras', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 51, 'code' => 'CG', 'name' => 'Congo', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 52, 'code' => 'CD', 'name' => 'República Democrática del Congo', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 53, 'code' => 'CK', 'name' => 'Islas Cook', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 54, 'code' => 'CR', 'name' => 'Costa Rica', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 55, 'code' => 'HR', 'name' => 'Croacia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 56, 'code' => 'CU', 'name' => 'Cuba', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 57, 'code' => 'CW', 'name' => 'Curazao', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 58, 'code' => 'CY', 'name' => 'Chipre', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 59, 'code' => 'CZ', 'name' => 'Chequia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 60, 'code' => 'CI', 'name' => 'Côte d’Ivoire', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 61, 'code' => 'DK', 'name' => 'Dinamarca', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 62, 'code' => 'DJ', 'name' => 'Yibuti', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 63, 'code' => 'DM', 'name' => 'Dominica', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 64, 'code' => 'DO', 'name' => 'República Dominicana', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 65, 'code' => 'EC', 'name' => 'Ecuador', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 66, 'code' => 'EG', 'name' => 'Egipto', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 67, 'code' => 'SV', 'name' => 'El Salvador', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 68, 'code' => 'GQ', 'name' => 'Guinea Ecuatorial', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 69, 'code' => 'ER', 'name' => 'Eritrea', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 70, 'code' => 'EE', 'name' => 'Estonia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 71, 'code' => 'SZ', 'name' => 'Esuatini', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 72, 'code' => 'ET', 'name' => 'Etiopía', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 73, 'code' => 'FK', 'name' => 'Islas Malvinas', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 74, 'code' => 'FO', 'name' => 'Islas Feroe', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 75, 'code' => 'FJ', 'name' => 'Fiyi', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 76, 'code' => 'FI', 'name' => 'Finlandia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 77, 'code' => 'FR', 'name' => 'Francia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 78, 'code' => 'GF', 'name' => 'Guayana Francesa', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 79, 'code' => 'PF', 'name' => 'Polinesia Francesa', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 80, 'code' => 'TF', 'name' => 'Territorios Australes Franceses', 'continent' => 'Antarctica', 'continent_code' => 'AN', 'active' => 0],
            ['id' => 81, 'code' => 'GA', 'name' => 'Gabón', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 82, 'code' => 'GM', 'name' => 'Gambia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 83, 'code' => 'GE', 'name' => 'Georgia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 84, 'code' => 'DE', 'name' => 'Alemania', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 85, 'code' => 'GH', 'name' => 'Ghana', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 86, 'code' => 'GI', 'name' => 'Gibraltar', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 87, 'code' => 'GR', 'name' => 'Grecia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 88, 'code' => 'GL', 'name' => 'Groenlandia', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 89, 'code' => 'GD', 'name' => 'Granada', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 90, 'code' => 'GP', 'name' => 'Guadalupe', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 91, 'code' => 'GU', 'name' => 'Guam', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 92, 'code' => 'GT', 'name' => 'Guatemala', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 1],
            ['id' => 93, 'code' => 'GG', 'name' => 'Guernesey', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 94, 'code' => 'GN', 'name' => 'Guinea', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 95, 'code' => 'GW', 'name' => 'Guinea-Bisáu', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 96, 'code' => 'GY', 'name' => 'Guyana', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 97, 'code' => 'HT', 'name' => 'Haití', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 98, 'code' => 'HM', 'name' => 'Islas Heard y McDonald', 'continent' => 'Antarctica', 'continent_code' => 'AN', 'active' => 0],
            ['id' => 99, 'code' => 'HN', 'name' => 'Honduras', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 1],
            ['id' => 100, 'code' => 'HK', 'name' => 'RAE de Hong Kong (China)', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 101, 'code' => 'HU', 'name' => 'Hungría', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 102, 'code' => 'IS', 'name' => 'Islandia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 103, 'code' => 'IN', 'name' => 'India', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 104, 'code' => 'ID', 'name' => 'Indonesia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 105, 'code' => 'IR', 'name' => 'Irán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 106, 'code' => 'IQ', 'name' => 'Irak', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 107, 'code' => 'IE', 'name' => 'Irlanda', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 108, 'code' => 'IM', 'name' => 'Isla de Man', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 109, 'code' => 'IL', 'name' => 'Israel', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 110, 'code' => 'IT', 'name' => 'Italia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 111, 'code' => 'JM', 'name' => 'Jamaica', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 112, 'code' => 'JP', 'name' => 'Japón', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 113, 'code' => 'JE', 'name' => 'Jersey', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 114, 'code' => 'JO', 'name' => 'Jordania', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 115, 'code' => 'KZ', 'name' => 'Kazajistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 116, 'code' => 'KE', 'name' => 'Kenia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 117, 'code' => 'KI', 'name' => 'Kiribati', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 118, 'code' => 'KP', 'name' => 'Corea del Norte', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 119, 'code' => 'KR', 'name' => 'Corea del Sur', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 120, 'code' => 'XK', 'name' => 'Kosovo', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 121, 'code' => 'KW', 'name' => 'Kuwait', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 122, 'code' => 'KG', 'name' => 'Kirguistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 123, 'code' => 'LA', 'name' => 'Laos', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 124, 'code' => 'LV', 'name' => 'Letonia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 125, 'code' => 'LB', 'name' => 'Líbano', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 126, 'code' => 'LS', 'name' => 'Lesoto', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 127, 'code' => 'LR', 'name' => 'Liberia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 128, 'code' => 'LY', 'name' => 'Libia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 129, 'code' => 'LI', 'name' => 'Liechtenstein', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 130, 'code' => 'LT', 'name' => 'Lituania', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 131, 'code' => 'LU', 'name' => 'Luxemburgo', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 132, 'code' => 'MO', 'name' => 'RAE de Macao (China)', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 133, 'code' => 'MK', 'name' => 'Macedonia del Norte', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 134, 'code' => 'MG', 'name' => 'Madagascar', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 135, 'code' => 'MW', 'name' => 'Malaui', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 136, 'code' => 'MY', 'name' => 'Malasia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 137, 'code' => 'MV', 'name' => 'Maldivas', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 138, 'code' => 'ML', 'name' => 'Mali', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 139, 'code' => 'MT', 'name' => 'Malta', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 140, 'code' => 'MH', 'name' => 'Islas Marshall', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 141, 'code' => 'MQ', 'name' => 'Martinica', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 142, 'code' => 'MR', 'name' => 'Mauritania', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 143, 'code' => 'MU', 'name' => 'Mauricio', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 144, 'code' => 'YT', 'name' => 'Mayotte', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 145, 'code' => 'MX', 'name' => 'México', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 1],
            ['id' => 146, 'code' => 'FM', 'name' => 'Micronesia', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 147, 'code' => 'MD', 'name' => 'Moldavia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 148, 'code' => 'MC', 'name' => 'Mónaco', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 149, 'code' => 'MN', 'name' => 'Mongolia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 150, 'code' => 'ME', 'name' => 'Montenegro', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 151, 'code' => 'MS', 'name' => 'Montserrat', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 152, 'code' => 'MA', 'name' => 'Marruecos', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 153, 'code' => 'MZ', 'name' => 'Mozambique', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 154, 'code' => 'MM', 'name' => 'Myanmar (Birmania)', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 155, 'code' => 'NA', 'name' => 'Namibia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 156, 'code' => 'NR', 'name' => 'Nauru', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 157, 'code' => 'NP', 'name' => 'Nepal', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 158, 'code' => 'NL', 'name' => 'Países Bajos', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 159, 'code' => 'AN', 'name' => 'Curazao', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 160, 'code' => 'NC', 'name' => 'Nueva Caledonia', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 161, 'code' => 'NZ', 'name' => 'Nueva Zelanda', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 162, 'code' => 'NI', 'name' => 'Nicaragua', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 1],
            ['id' => 163, 'code' => 'NE', 'name' => 'Níger', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 164, 'code' => 'NG', 'name' => 'Nigeria', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 165, 'code' => 'NU', 'name' => 'Niue', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 166, 'code' => 'NF', 'name' => 'Isla Norfolk', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 167, 'code' => 'MP', 'name' => 'Islas Marianas del Norte', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 168, 'code' => 'NO', 'name' => 'Noruega', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 169, 'code' => 'OM', 'name' => 'Omán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 170, 'code' => 'PK', 'name' => 'Pakistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 171, 'code' => 'PW', 'name' => 'Palaos', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 172, 'code' => 'PS', 'name' => 'Territorios Palestinos', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 173, 'code' => 'PA', 'name' => 'Panamá', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 174, 'code' => 'PG', 'name' => 'Papúa Nueva Guinea', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 175, 'code' => 'PY', 'name' => 'Paraguay', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 176, 'code' => 'PE', 'name' => 'Perú', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 177, 'code' => 'PH', 'name' => 'Filipinas', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 178, 'code' => 'PN', 'name' => 'Islas Pitcairn', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 179, 'code' => 'PL', 'name' => 'Polonia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 180, 'code' => 'PT', 'name' => 'Portugal', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 181, 'code' => 'PR', 'name' => 'Puerto Rico', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 182, 'code' => 'QA', 'name' => 'Catar', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 183, 'code' => 'RE', 'name' => 'Reunión', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 184, 'code' => 'RO', 'name' => 'Rumanía', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 185, 'code' => 'RU', 'name' => 'Rusia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 186, 'code' => 'RW', 'name' => 'Ruanda', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 187, 'code' => 'BL', 'name' => 'San Bartolomé', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 188, 'code' => 'SH', 'name' => 'Santa Elena', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 189, 'code' => 'KN', 'name' => 'San Cristóbal y Nieves', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 190, 'code' => 'LC', 'name' => 'Santa Lucía', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 191, 'code' => 'MF', 'name' => 'San Martín', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 192, 'code' => 'PM', 'name' => 'San Pedro y Miquelón', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 193, 'code' => 'VC', 'name' => 'San Vicente y las Granadinas', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 194, 'code' => 'WS', 'name' => 'Samoa', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 195, 'code' => 'SM', 'name' => 'San Marino', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 196, 'code' => 'ST', 'name' => 'Santo Tomé y Príncipe', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 197, 'code' => 'SA', 'name' => 'Arabia Saudí', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 198, 'code' => 'SN', 'name' => 'Senegal', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 199, 'code' => 'RS', 'name' => 'Serbia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 200, 'code' => 'CS', 'name' => 'Serbia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 201, 'code' => 'SC', 'name' => 'Seychelles', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 202, 'code' => 'SL', 'name' => 'Sierra Leona', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 203, 'code' => 'SG', 'name' => 'Singapur', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 204, 'code' => 'SX', 'name' => 'Sint Maarten', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 205, 'code' => 'SK', 'name' => 'Eslovaquia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 206, 'code' => 'SI', 'name' => 'Eslovenia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 207, 'code' => 'SB', 'name' => 'Islas Salomón', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 208, 'code' => 'SO', 'name' => 'Somalia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 209, 'code' => 'ZA', 'name' => 'Sudáfrica', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 210, 'code' => 'GS', 'name' => 'Islas Georgia del Sur y Sandwich del Sur', 'continent' => 'Antarctica', 'continent_code' => 'AN', 'active' => 0],
            ['id' => 211, 'code' => 'SS', 'name' => 'Sudán del Sur', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 212, 'code' => 'ES', 'name' => 'España', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 1],
            ['id' => 213, 'code' => 'LK', 'name' => 'Sri Lanka', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 214, 'code' => 'SD', 'name' => 'Sudán', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 215, 'code' => 'SR', 'name' => 'Surinam', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 216, 'code' => 'SJ', 'name' => 'Svalbard y Jan Mayen', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 217, 'code' => 'SE', 'name' => 'Suecia', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 218, 'code' => 'CH', 'name' => 'Suiza', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 219, 'code' => 'SY', 'name' => 'Siria', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 220, 'code' => 'TW', 'name' => 'Taiwán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 221, 'code' => 'TJ', 'name' => 'Tayikistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 222, 'code' => 'TZ', 'name' => 'Tanzania', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 223, 'code' => 'TH', 'name' => 'Tailandia', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 224, 'code' => 'TL', 'name' => 'Timor-Leste', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 225, 'code' => 'TG', 'name' => 'Togo', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 226, 'code' => 'TK', 'name' => 'Tokelau', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 227, 'code' => 'TO', 'name' => 'Tonga', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 228, 'code' => 'TT', 'name' => 'Trinidad y Tobago', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 229, 'code' => 'TN', 'name' => 'Túnez', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 230, 'code' => 'TR', 'name' => 'Turquía', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 231, 'code' => 'TM', 'name' => 'Turkmenistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 232, 'code' => 'TC', 'name' => 'Islas Turcas y Caicos', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 233, 'code' => 'TV', 'name' => 'Tuvalu', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 234, 'code' => 'UM', 'name' => 'Islas menores alejadas de EE. UU.', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 235, 'code' => 'UG', 'name' => 'Uganda', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 236, 'code' => 'UA', 'name' => 'Ucrania', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 237, 'code' => 'AE', 'name' => 'Emiratos Árabes Unidos', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 238, 'code' => 'GB', 'name' => 'Reino Unido', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 239, 'code' => 'US', 'name' => 'Estados Unidos', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 1],
            ['id' => 240, 'code' => 'UY', 'name' => 'Uruguay', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 1],
            ['id' => 241, 'code' => 'UZ', 'name' => 'Uzbekistán', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 242, 'code' => 'VU', 'name' => 'Vanuatu', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 243, 'code' => 'VA', 'name' => 'Ciudad del Vaticano', 'continent' => 'Europe', 'continent_code' => 'EU', 'active' => 0],
            ['id' => 244, 'code' => 'VE', 'name' => 'Venezuela', 'continent' => 'South America', 'continent_code' => 'SA', 'active' => 0],
            ['id' => 245, 'code' => 'VN', 'name' => 'Vietnam', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 246, 'code' => 'VG', 'name' => 'Islas Vírgenes Británicas', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 247, 'code' => 'VI', 'name' => 'Islas Vírgenes de EE. UU.', 'continent' => 'North America', 'continent_code' => 'NA', 'active' => 0],
            ['id' => 248, 'code' => 'WF', 'name' => 'Wallis y Futuna', 'continent' => 'Australia (Oceania)', 'continent_code' => 'OC', 'active' => 0],
            ['id' => 249, 'code' => 'EH', 'name' => 'Sáhara Occidental', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 250, 'code' => 'YE', 'name' => 'Yemen', 'continent' => 'Asia', 'continent_code' => 'AS', 'active' => 0],
            ['id' => 251, 'code' => 'ZM', 'name' => 'Zambia', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0],
            ['id' => 252, 'code' => 'ZW', 'name' => 'Zimbabue', 'continent' => 'Africa', 'continent_code' => 'AF', 'active' => 0]
        ]);

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
