<?php

use App\Models\Timezone;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Ramsey\Uuid\Type\Time;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('timezones', function (Blueprint $table) {
            $table->id();
            $table->string('timezone')->unique();
        });

        Timezone::insert([
            ['timezone' => 'America/Adak'],
            ['timezone' => 'America/Anchorage'],
            ['timezone' => 'America/Araguaina'],
            ['timezone' => 'America/Argentina/Buenos_Aires'],
            ['timezone' => 'America/Argentina/Catamarca'],
            ['timezone' => 'America/Argentina/Cordoba'],
            ['timezone' => 'America/Argentina/Jujuy'],
            ['timezone' => 'America/Argentina/La_Rioja'],
            ['timezone' => 'America/Argentina/Mendoza'],
            ['timezone' => 'America/Argentina/Rio_Gallegos'],
            ['timezone' => 'America/Argentina/Salta'],
            ['timezone' => 'America/Argentina/San_Juan'],
            ['timezone' => 'America/Argentina/San_Luis'],
            ['timezone' => 'America/Argentina/Tucuman'],
            ['timezone' => 'America/Argentina/Ushuaia'],
            ['timezone' => 'America/Asuncion'],
            ['timezone' => 'America/Bahia'],
            ['timezone' => 'America/Bahia_Banderas'],
            ['timezone' => 'America/Barbados'],
            ['timezone' => 'America/Belem'],
            ['timezone' => 'America/Belize'],
            ['timezone' => 'America/Boa_Vista'],
            ['timezone' => 'America/Bogota'],
            ['timezone' => 'America/Boise'],
            ['timezone' => 'America/Cambridge_Bay'],
            ['timezone' => 'America/Campo_Grande'],
            ['timezone' => 'America/Cancun'],
            ['timezone' => 'America/Caracas'],
            ['timezone' => 'America/Cayenne'],
            ['timezone' => 'America/Chicago'],
            ['timezone' => 'America/Chihuahua'],
            ['timezone' => 'America/Costa_Rica'],
            ['timezone' => 'America/Cuiaba'],
            ['timezone' => 'America/Curacao'],
            ['timezone' => 'America/Danmarkshavn'],
            ['timezone' => 'America/Dawson'],
            ['timezone' => 'America/Dawson_Creek'],
            ['timezone' => 'America/Denver'],
            ['timezone' => 'America/Detroit'],
            ['timezone' => 'America/Edmonton'],
            ['timezone' => 'America/Eirunepe'],
            ['timezone' => 'America/El_Salvador'],
            ['timezone' => 'America/Fortaleza'],
            ['timezone' => 'America/Glace_Bay'],
            ['timezone' => 'America/Godthab'],
            ['timezone' => 'America/Goose_Bay'],
            ['timezone' => 'America/Grand_Turk'],
            ['timezone' => 'America/Guatemala'],
            ['timezone' => 'America/Guayaquil'],
            ['timezone' => 'America/Guyana'],
            ['timezone' => 'America/Halifax'],
            ['timezone' => 'America/Havana'],
            ['timezone' => 'America/Hermosillo'],
            ['timezone' => 'America/Indiana/Indianapolis'],
            ['timezone' => 'America/Indiana/Knox'],
            ['timezone' => 'America/Indiana/Marengo'],
            ['timezone' => 'America/Indiana/Petersburg'],
            ['timezone' => 'America/Indiana/Tell_City'],
            ['timezone' => 'America/Indiana/Vevay'],
            ['timezone' => 'America/Indiana/Vincennes'],
            ['timezone' => 'America/Indiana/Winamac'],
            ['timezone' => 'America/Inuvik'],
            ['timezone' => 'America/Iqaluit'],
            ['timezone' => 'America/Jamaica'],
            ['timezone' => 'America/Juneau'],
            ['timezone' => 'America/La_Paz'],
            ['timezone' => 'America/Lima'],
            ['timezone' => 'America/Los_Angeles'],
            ['timezone' => 'America/Maceio'],
            ['timezone' => 'America/Managua'],
            ['timezone' => 'America/Manaus'],
            ['timezone' => 'America/Martinique'],
            ['timezone' => 'America/Matamoros'],
            ['timezone' => 'America/Mazatlan'],
            ['timezone' => 'America/Menominee'],
            ['timezone' => 'America/Merida'],
            ['timezone' => 'America/Metlakatla'],
            ['timezone' => 'America/Mexico_City'],
            ['timezone' => 'America/Miquelon'],
            ['timezone' => 'America/Moncton'],
            ['timezone' => 'America/Monterrey'],
            ['timezone' => 'America/Montevideo'],
            ['timezone' => 'America/Nassau'],
            ['timezone' => 'America/New_York'],
            ['timezone' => 'America/Nipigon'],
            ['timezone' => 'America/Nome'],
            ['timezone' => 'America/Noronha'],
            ['timezone' => 'America/North_Dakota/Beulah'],
            ['timezone' => 'America/North_Dakota/Center'],
            ['timezone' => 'America/North_Dakota/New_Salem'],
            ['timezone' => 'America/Ojinaga'],
            ['timezone' => 'America/Panama'],
            ['timezone' => 'America/Pangnirtung'],
            ['timezone' => 'America/Paramaribo'],
            ['timezone' => 'America/Phoenix'],
            ['timezone' => 'America/Port-au-Prince'],
            ['timezone' => 'America/Port_of_Spain'],
            ['timezone' => 'America/Porto_Velho'],
            ['timezone' => 'America/Puerto_Rico'],
            ['timezone' => 'America/Punta_Arenas'],
            ['timezone' => 'America/Rainy_River'],
            ['timezone' => 'America/Rankin_Inlet'],
            ['timezone' => 'America/Recife'],
            ['timezone' => 'America/Regina'],
            ['timezone' => 'America/Resolute'],
            ['timezone' => 'America/Rio_Branco'],
            ['timezone' => 'America/Santarem'],
            ['timezone' => 'America/Santiago'],
            ['timezone' => 'America/Santo_Domingo'],
            ['timezone' => 'America/Sao_Paulo'],
            ['timezone' => 'America/Scoresbysund'],
            ['timezone' => 'America/Sitka'],
            ['timezone' => 'America/St_Johns'],
            ['timezone' => 'America/Swift_Current'],
            ['timezone' => 'America/Tegucigalpa'],
            ['timezone' => 'America/Thule'],
            ['timezone' => 'America/Tijuana'],
            ['timezone' => 'America/Toronto'],
            ['timezone' => 'America/Vancouver'],
            ['timezone' => 'America/Whitehorse'],
            ['timezone' => 'America/Winnipeg'],
            ['timezone' => 'America/Yakutat'],
            ['timezone' => 'America/Yellowknife'],
            ['timezone' => 'Europe/Amsterdam'],
            ['timezone' => 'Europe/Andorra'],
            ['timezone' => 'Europe/Astrakhan'],
            ['timezone' => 'Europe/Athens'],
            ['timezone' => 'Europe/Belgrade'],
            ['timezone' => 'Europe/Berlin'],
            ['timezone' => 'Europe/Bratislava'],
            ['timezone' => 'Europe/Brussels'],
            ['timezone' => 'Europe/Bucharest'],
            ['timezone' => 'Europe/Budapest'],
            ['timezone' => 'Europe/Busingen'],
            ['timezone' => 'Europe/Chisinau'],
            ['timezone' => 'Europe/Copenhagen'],
            ['timezone' => 'Europe/Dublin'],
            ['timezone' => 'Europe/Gibraltar'],
            ['timezone' => 'Europe/Guernsey'],
            ['timezone' => 'Europe/Helsinki'],
            ['timezone' => 'Europe/Isle_of_Man'],
            ['timezone' => 'Europe/Istanbul'],
            ['timezone' => 'Europe/Jersey'],
            ['timezone' => 'Europe/Kaliningrad'],
            ['timezone' => 'Europe/Kiev'],
            ['timezone' => 'Europe/Kirov'],
            ['timezone' => 'Europe/Lisbon'],
            ['timezone' => 'Europe/Ljubljana'],
            ['timezone' => 'Europe/London'],
            ['timezone' => 'Europe/Luxembourg'],
            ['timezone' => 'Europe/Madrid'],
            ['timezone' => 'Europe/Malta'],
            ['timezone' => 'Europe/Mariehamn'],
            ['timezone' => 'Europe/Minsk'],
            ['timezone' => 'Europe/Monaco'],
            ['timezone' => 'Europe/Moscow'],
            ['timezone' => 'Europe/Oslo'],
            ['timezone' => 'Europe/Paris'],
            ['timezone' => 'Europe/Podgorica'],
            ['timezone' => 'Europe/Prague'],
            ['timezone' => 'Europe/Riga'],
            ['timezone' => 'Europe/Rome'],
            ['timezone' => 'Europe/Samara'],
            ['timezone' => 'Europe/San_Marino'],
            ['timezone' => 'Europe/Sarajevo'],
            ['timezone' => 'Europe/Saratov'],
            ['timezone' => 'Europe/Simferopol'],
            ['timezone' => 'Europe/Skopje'],
            ['timezone' => 'Europe/Sofia'],
            ['timezone' => 'Europe/Stockholm'],
            ['timezone' => 'Europe/Tallinn'],
            ['timezone' => 'Europe/Tirane'],
            ['timezone' => 'Europe/Ulyanovsk'],
            ['timezone' => 'Europe/Uzhgorod'],
            ['timezone' => 'Europe/Vaduz'],
            ['timezone' => 'Europe/Vatican'],
            ['timezone' => 'Europe/Vienna'],
            ['timezone' => 'Europe/Vilnius'],
            ['timezone' => 'Europe/Volgograd'],
            ['timezone' => 'Europe/Warsaw'],
            ['timezone' => 'Europe/Zagreb'],
            ['timezone' => 'Europe/Zaporozhye'],
            ['timezone' => 'Europe/Zurich'],
            ['timezone' => 'Asia/Aden'],
            ['timezone' => 'Asia/Almaty'],
            ['timezone' => 'Asia/Amman'],
            ['timezone' => 'Asia/Anadyr'],
            ['timezone' => 'Asia/Aqtau'],
            ['timezone' => 'Asia/Aqtobe'],
            ['timezone' => 'Asia/Ashgabat'],
            ['timezone' => 'Asia/Atyrau'],
            ['timezone' => 'Asia/Baghdad'],
            ['timezone' => 'Asia/Bahrain'],
            ['timezone' => 'Asia/Baku'],
            ['timezone' => 'Asia/Bangkok'],
            ['timezone' => 'Asia/Barnaul'],
            ['timezone' => 'Asia/Beirut'],
            ['timezone' => 'Asia/Bishkek'],
            ['timezone' => 'Asia/Brunei'],
            ['timezone' => 'Asia/Chita'],
            ['timezone' => 'Asia/Choibalsan'],
            ['timezone' => 'Asia/Colombo'],
            ['timezone' => 'Asia/Damascus'],
            ['timezone' => 'Asia/Dhaka'],
            ['timezone' => 'Asia/Dili'],
            ['timezone' => 'Asia/Dubai'],
            ['timezone' => 'Asia/Dushanbe'],
            ['timezone' => 'Asia/Famagusta'],
            ['timezone' => 'Asia/Gaza'],
            ['timezone' => 'Asia/Hebron'],
            ['timezone' => 'Asia/Ho_Chi_Minh'],
            ['timezone' => 'Asia/Hong_Kong'],
            ['timezone' => 'Asia/Hovd'],
            ['timezone' => 'Asia/Irkutsk'],
            ['timezone' => 'Asia/Jakarta'],
            ['timezone' => 'Asia/Jayapura'],
            ['timezone' => 'Asia/Jerusalem'],
            ['timezone' => 'Asia/Kabul'],
            ['timezone' => 'Asia/Kamchatka'],
            ['timezone' => 'Asia/Karachi'],
            ['timezone' => 'Asia/Kathmandu'],
            ['timezone' => 'Asia/Khandyga'],
            ['timezone' => 'Asia/Kolkata'],
            ['timezone' => 'Asia/Krasnoyarsk'],
            ['timezone' => 'Asia/Kuala_Lumpur'],
            ['timezone' => 'Asia/Kuching'],
            ['timezone' => 'Asia/Kuwait'],
            ['timezone' => 'Asia/Macau'],
            ['timezone' => 'Asia/Magadan'],
            ['timezone' => 'Asia/Makassar'],
            ['timezone' => 'Asia/Manila'],
            ['timezone' => 'Asia/Muscat'],
            ['timezone' => 'Asia/Nicosia'],
            ['timezone' => 'Asia/Novokuznetsk'],
            ['timezone' => 'Asia/Novosibirsk'],
            ['timezone' => 'Asia/Omsk'],
            ['timezone' => 'Asia/Oral'],
            ['timezone' => 'Asia/Phnom_Penh'],
            ['timezone' => 'Asia/Pontianak'],
            ['timezone' => 'Asia/Pyongyang'],
            ['timezone' => 'Asia/Qatar'],
            ['timezone' => 'Asia/Qostanay'],
            ['timezone' => 'Asia/Qyzylorda'],
            ['timezone' => 'Asia/Riyadh'],
            ['timezone' => 'Asia/Sakhalin'],
            ['timezone' => 'Asia/Samarkand'],
            ['timezone' => 'Asia/Seoul'],
            ['timezone' => 'Asia/Shanghai'],
            ['timezone' => 'Asia/Singapore'],
            ['timezone' => 'Asia/Srednekolymsk'],
            ['timezone' => 'Asia/Taipei'],
            ['timezone' => 'Asia/Tashkent'],
            ['timezone' => 'Asia/Tbilisi'],
            ['timezone' => 'Asia/Tehran'],
            ['timezone' => 'Asia/Thimphu'],
            ['timezone' => 'Asia/Tokyo'],
            ['timezone' => 'Asia/Tomsk'],
            ['timezone' => 'Asia/Ulaanbaatar'],
            ['timezone' => 'Asia/Urumqi'],
            ['timezone' => 'Asia/Ust-Nera'],
            ['timezone' => 'Asia/Vientiane'],
            ['timezone' => 'Asia/Vladivostok'],
            ['timezone' => 'Asia/Yakutsk'],
            ['timezone' => 'Asia/Yangon'],
            ['timezone' => 'Asia/Yekaterinburg'],
            ['timezone' => 'Asia/Yerevan'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('timezones');
    }
};
