<?php

use App\Models\CountryDivision;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('country_divisions', function (Blueprint $table) {
            $table->id();
            $table->string('state_name');
            $table->string('state_code', 100);
            $table->string('country_code', 2);
        });

        CountryDivision::insert([
            ['id' => 160, 'state_name' => 'Ciudad Autónoma de Buenos Aires', 'state_code' => 'C', 'country_code' => 'AR'],
            ['id' => 161, 'state_name' => 'Buenos Aires', 'state_code' => 'B', 'country_code' => 'AR'],
            ['id' => 162, 'state_name' => 'Catamarca', 'state_code' => 'K', 'country_code' => 'AR'],
            ['id' => 163, 'state_name' => 'Chaco', 'state_code' => 'H', 'country_code' => 'AR'],
            ['id' => 164, 'state_name' => 'Chubut', 'state_code' => 'U', 'country_code' => 'AR'],
            ['id' => 165, 'state_name' => 'Córdoba', 'state_code' => 'X', 'country_code' => 'AR'],
            ['id' => 166, 'state_name' => 'Corrientes', 'state_code' => 'W', 'country_code' => 'AR'],
            ['id' => 167, 'state_name' => 'Entre Ríos', 'state_code' => 'E', 'country_code' => 'AR'],
            ['id' => 168, 'state_name' => 'Formosa', 'state_code' => 'P', 'country_code' => 'AR'],
            ['id' => 169, 'state_name' => 'Jujuy', 'state_code' => 'Y', 'country_code' => 'AR'],
            ['id' => 170, 'state_name' => 'La Pampa', 'state_code' => 'L', 'country_code' => 'AR'],
            ['id' => 171, 'state_name' => 'La Rioja', 'state_code' => 'F', 'country_code' => 'AR'],
            ['id' => 172, 'state_name' => 'Mendoza', 'state_code' => 'M', 'country_code' => 'AR'],
            ['id' => 173, 'state_name' => 'Misiones', 'state_code' => 'N', 'country_code' => 'AR'],
            ['id' => 174, 'state_name' => 'Neuquén', 'state_code' => 'Q', 'country_code' => 'AR'],
            ['id' => 175, 'state_name' => 'Río Negro', 'state_code' => 'R', 'country_code' => 'AR'],
            ['id' => 176, 'state_name' => 'Salta', 'state_code' => 'A', 'country_code' => 'AR'],
            ['id' => 177, 'state_name' => 'San Juan', 'state_code' => 'J', 'country_code' => 'AR'],
            ['id' => 178, 'state_name' => 'San Luis', 'state_code' => 'D', 'country_code' => 'AR'],
            ['id' => 179, 'state_name' => 'Santa Cruz', 'state_code' => 'Z', 'country_code' => 'AR'],
            ['id' => 180, 'state_name' => 'Santa Fe', 'state_code' => 'S', 'country_code' => 'AR'],
            ['id' => 181, 'state_name' => 'Santiago del Estero', 'state_code' => 'G', 'country_code' => 'AR'],
            ['id' => 182, 'state_name' => 'Tierra del Fuego', 'state_code' => 'V', 'country_code' => 'AR'],
            ['id' => 183, 'state_name' => 'Tucumán', 'state_code' => 'T', 'country_code' => 'AR'],
            ['id' => 195, 'state_name' => 'Australian Capital Territory', 'state_code' => 'ACT', 'country_code' => 'AU'],
            ['id' => 196, 'state_name' => 'New South Wales', 'state_code' => 'NSW', 'country_code' => 'AU'],
            ['id' => 197, 'state_name' => 'Northern Territory', 'state_code' => 'NT', 'country_code' => 'AU'],
            ['id' => 198, 'state_name' => 'Queensland', 'state_code' => 'QLD', 'country_code' => 'AU'],
            ['id' => 199, 'state_name' => 'South Australia', 'state_code' => 'SA', 'country_code' => 'AU'],
            ['id' => 200, 'state_name' => 'Tasmania', 'state_code' => 'TAS', 'country_code' => 'AU'],
            ['id' => 201, 'state_name' => 'Victoria', 'state_code' => 'VIC', 'country_code' => 'AU'],
            ['id' => 202, 'state_name' => 'Western Australia', 'state_code' => 'WA', 'country_code' => 'AU'],
            ['id' => 758, 'state_name' => 'Antofagasta Region', 'state_code' => 'AN', 'country_code' => 'CL'],
            ['id' => 759, 'state_name' => 'Araucanía Region', 'state_code' => 'AR', 'country_code' => 'CL'],
            ['id' => 760, 'state_name' => 'Arica y Parinacota Region', 'state_code' => 'AP', 'country_code' => 'CL'],
            ['id' => 761, 'state_name' => 'Atacama Region', 'state_code' => 'AT', 'country_code' => 'CL'],
            ['id' => 762, 'state_name' => 'Aysén Region', 'state_code' => 'AI', 'country_code' => 'CL'],
            ['id' => 763, 'state_name' => 'Bío Bío Region', 'state_code' => 'BI', 'country_code' => 'CL'],
            ['id' => 764, 'state_name' => 'Coquimbo Region', 'state_code' => 'CO', 'country_code' => 'CL'],
            ['id' => 765, 'state_name' => 'Los Lagos Region', 'state_code' => 'LL', 'country_code' => 'CL'],
            ['id' => 766, 'state_name' => 'Los Ríos Region', 'state_code' => 'LR', 'country_code' => 'CL'],
            ['id' => 767, 'state_name' => 'Magellan and the Chilean Antarctic Region', 'state_code' => 'MA', 'country_code' => 'CL'],
            ['id' => 768, 'state_name' => 'Maule Region', 'state_code' => 'ML', 'country_code' => 'CL'],
            ['id' => 769, 'state_name' => 'Ñuble Region', 'state_code' => 'NB', 'country_code' => 'CL'],
            ['id' => 770, 'state_name' => 'O\'Higgins', 'state_code' => 'LI', 'country_code' => 'CL'],
            ['id' => 771, 'state_name' => 'Santiago Metropolitan Region', 'state_code' => 'RM', 'country_code' => 'CL'],
            ['id' => 772, 'state_name' => 'Tarapacá Region', 'state_code' => 'TA', 'country_code' => 'CL'],
            ['id' => 773, 'state_name' => 'Valparaíso', 'state_code' => 'VS', 'country_code' => 'CL'],
            ['id' => 808, 'state_name' => 'Amazonas', 'state_code' => 'AMA', 'country_code' => 'CO'],
            ['id' => 809, 'state_name' => 'Antioquia', 'state_code' => 'ANT', 'country_code' => 'CO'],
            ['id' => 810, 'state_name' => 'Arauca', 'state_code' => 'ARA', 'country_code' => 'CO'],
            ['id' => 811, 'state_name' => 'Archipelago of Saint Andréws, Providence and Saint Catalina', 'state_code' => 'SAP', 'country_code' => 'CO'],
            ['id' => 812, 'state_name' => 'Atlántico', 'state_code' => 'ATL', 'country_code' => 'CO'],
            ['id' => 813, 'state_name' => 'Bolívar', 'state_code' => 'BOL', 'country_code' => 'CO'],
            ['id' => 814, 'state_name' => 'Boyacá', 'state_code' => 'BOY', 'country_code' => 'CO'],
            ['id' => 815, 'state_name' => 'Caldas', 'state_code' => 'CAL', 'country_code' => 'CO'],
            ['id' => 816, 'state_name' => 'Caquetá', 'state_code' => 'CAQ', 'country_code' => 'CO'],
            ['id' => 817, 'state_name' => 'Casanare', 'state_code' => 'CAS', 'country_code' => 'CO'],
            ['id' => 818, 'state_name' => 'Cauca', 'state_code' => 'CAU', 'country_code' => 'CO'],
            ['id' => 819, 'state_name' => 'Cesar', 'state_code' => 'CES', 'country_code' => 'CO'],
            ['id' => 820, 'state_name' => 'Chocó', 'state_code' => 'CHO', 'country_code' => 'CO'],
            ['id' => 821, 'state_name' => 'Córdoba', 'state_code' => 'COR', 'country_code' => 'CO'],
            ['id' => 822, 'state_name' => 'Cundinamarca', 'state_code' => 'CUN', 'country_code' => 'CO'],
            ['id' => 823, 'state_name' => 'Guainía', 'state_code' => 'GUA', 'country_code' => 'CO'],
            ['id' => 824, 'state_name' => 'Guaviare', 'state_code' => 'GUV', 'country_code' => 'CO'],
            ['id' => 825, 'state_name' => 'Huila', 'state_code' => 'HUI', 'country_code' => 'CO'],
            ['id' => 826, 'state_name' => 'La Guajira', 'state_code' => 'LAG', 'country_code' => 'CO'],
            ['id' => 827, 'state_name' => 'Magdalena', 'state_code' => 'MAG', 'country_code' => 'CO'],
            ['id' => 828, 'state_name' => 'Meta', 'state_code' => 'MET', 'country_code' => 'CO'],
            ['id' => 829, 'state_name' => 'Nariño', 'state_code' => 'NAR', 'country_code' => 'CO'],
            ['id' => 830, 'state_name' => 'Norte de Santander', 'state_code' => 'NSA', 'country_code' => 'CO'],
            ['id' => 831, 'state_name' => 'Putumayo', 'state_code' => 'PUT', 'country_code' => 'CO'],
            ['id' => 832, 'state_name' => 'Quindío', 'state_code' => 'QUI', 'country_code' => 'CO'],
            ['id' => 833, 'state_name' => 'Risaralda', 'state_code' => 'RIS', 'country_code' => 'CO'],
            ['id' => 834, 'state_name' => 'Santander', 'state_code' => 'SAN', 'country_code' => 'CO'],
            ['id' => 835, 'state_name' => 'Sucre', 'state_code' => 'SUC', 'country_code' => 'CO'],
            ['id' => 836, 'state_name' => 'Tolima', 'state_code' => 'TOL', 'country_code' => 'CO'],
            ['id' => 837, 'state_name' => 'Valle del Cauca', 'state_code' => 'VAC', 'country_code' => 'CO'],
            ['id' => 838, 'state_name' => 'Vaupés', 'state_code' => 'VAU', 'country_code' => 'CO'],
            ['id' => 839, 'state_name' => 'Vichada', 'state_code' => 'VID', 'country_code' => 'CO'],
            ['id' => 1134, 'state_name' => 'Azuay', 'state_code' => 'A', 'country_code' => 'EC'],
            ['id' => 1135, 'state_name' => 'Bolívar', 'state_code' => 'B', 'country_code' => 'EC'],
            ['id' => 1136, 'state_name' => 'Cañar', 'state_code' => 'F', 'country_code' => 'EC'],
            ['id' => 1137, 'state_name' => 'Carchi', 'state_code' => 'C', 'country_code' => 'EC'],
            ['id' => 1138, 'state_name' => 'Chimborazo', 'state_code' => 'H', 'country_code' => 'EC'],
            ['id' => 1139, 'state_name' => 'Cotopaxi', 'state_code' => 'X', 'country_code' => 'EC'],
            ['id' => 1140, 'state_name' => 'El Oro', 'state_code' => 'O', 'country_code' => 'EC'],
            ['id' => 1141, 'state_name' => 'Esmeraldas', 'state_code' => 'E', 'country_code' => 'EC'],
            ['id' => 1142, 'state_name' => 'Galápagos', 'state_code' => 'W', 'country_code' => 'EC'],
            ['id' => 1143, 'state_name' => 'Guayas', 'state_code' => 'G', 'country_code' => 'EC'],
            ['id' => 1144, 'state_name' => 'Imbabura', 'state_code' => 'I', 'country_code' => 'EC'],
            ['id' => 1145, 'state_name' => 'Los Ríos', 'state_code' => 'R', 'country_code' => 'EC'],
            ['id' => 1146, 'state_name' => 'Manabí', 'state_code' => 'M', 'country_code' => 'EC'],
            ['id' => 1147, 'state_name' => 'Morona-Santiago', 'state_code' => 'S', 'country_code' => 'EC'],
            ['id' => 1148, 'state_name' => 'Napo', 'state_code' => 'N', 'country_code' => 'EC'],
            ['id' => 1149, 'state_name' => 'Orellana', 'state_code' => 'D', 'country_code' => 'EC'],
            ['id' => 1150, 'state_name' => 'Pastaza', 'state_code' => 'Y', 'country_code' => 'EC'],
            ['id' => 1151, 'state_name' => 'Pichincha', 'state_code' => 'P', 'country_code' => 'EC'],
            ['id' => 1152, 'state_name' => 'Santa Elena', 'state_code' => 'SE', 'country_code' => 'EC'],
            ['id' => 1153, 'state_name' => 'Santo Domingo de los Tsáchilas', 'state_code' => 'SD', 'country_code' => 'EC'],
            ['id' => 1154, 'state_name' => 'Sucumbíos', 'state_code' => 'U', 'country_code' => 'EC'],
            ['id' => 1155, 'state_name' => 'Tungurahua', 'state_code' => 'T', 'country_code' => 'EC'],
            ['id' => 1156, 'state_name' => 'Zamora-Chinchipe', 'state_code' => 'Z', 'country_code' => 'EC'],
            ['id' => 1420, 'state_name' => 'Alta Verapaz', 'state_code' => 'AV', 'country_code' => 'GT'],
            ['id' => 1421, 'state_name' => 'Baja Verapaz', 'state_code' => 'BV', 'country_code' => 'GT'],
            ['id' => 1422, 'state_name' => 'Chimaltenango', 'state_code' => 'CM', 'country_code' => 'GT'],
            ['id' => 1423, 'state_name' => 'Chiquimula', 'state_code' => 'CQ', 'country_code' => 'GT'],
            ['id' => 1424, 'state_name' => 'El Progreso', 'state_code' => 'PR', 'country_code' => 'GT'],
            ['id' => 1425, 'state_name' => 'Escuintla', 'state_code' => 'ES', 'country_code' => 'GT'],
            ['id' => 1426, 'state_name' => 'Guatemala', 'state_code' => 'GU', 'country_code' => 'GT'],
            ['id' => 1427, 'state_name' => 'Huehuetenango', 'state_code' => 'HU', 'country_code' => 'GT'],
            ['id' => 1428, 'state_name' => 'Izabal', 'state_code' => 'IZ', 'country_code' => 'GT'],
            ['id' => 1429, 'state_name' => 'Jalapa', 'state_code' => 'JA', 'country_code' => 'GT'],
            ['id' => 1430, 'state_name' => 'Jutiapa', 'state_code' => 'JU', 'country_code' => 'GT'],
            ['id' => 1431, 'state_name' => 'Petén', 'state_code' => 'PE', 'country_code' => 'GT'],
            ['id' => 1432, 'state_name' => 'Quetzaltenango', 'state_code' => 'QZ', 'country_code' => 'GT'],
            ['id' => 1433, 'state_name' => 'Quiché', 'state_code' => 'QC', 'country_code' => 'GT'],
            ['id' => 1434, 'state_name' => 'Retalhuleu', 'state_code' => 'RE', 'country_code' => 'GT'],
            ['id' => 1435, 'state_name' => 'Sacatepéquez', 'state_code' => 'SA', 'country_code' => 'GT'],
            ['id' => 1436, 'state_name' => 'San Marcos', 'state_code' => 'SM', 'country_code' => 'GT'],
            ['id' => 1437, 'state_name' => 'Santa Rosa', 'state_code' => 'SR', 'country_code' => 'GT'],
            ['id' => 1438, 'state_name' => 'Sololá', 'state_code' => 'SO', 'country_code' => 'GT'],
            ['id' => 1439, 'state_name' => 'Suchitepéquez', 'state_code' => 'SU', 'country_code' => 'GT'],
            ['id' => 1440, 'state_name' => 'Totonicapán', 'state_code' => 'TO', 'country_code' => 'GT'],
            ['id' => 1512, 'state_name' => 'Atlántida', 'state_code' => 'AT', 'country_code' => 'HN'],
            ['id' => 1513, 'state_name' => 'Bay Islands', 'state_code' => 'IB', 'country_code' => 'HN'],
            ['id' => 1514, 'state_name' => 'Choluteca', 'state_code' => 'CH', 'country_code' => 'HN'],
            ['id' => 1515, 'state_name' => 'Colón', 'state_code' => 'CL', 'country_code' => 'HN'],
            ['id' => 1516, 'state_name' => 'Comayagua', 'state_code' => 'CM', 'country_code' => 'HN'],
            ['id' => 1517, 'state_name' => 'Copán', 'state_code' => 'CP', 'country_code' => 'HN'],
            ['id' => 1518, 'state_name' => 'Cortés', 'state_code' => 'CR', 'country_code' => 'HN'],
            ['id' => 1519, 'state_name' => 'El Paraíso', 'state_code' => 'EP', 'country_code' => 'HN'],
            ['id' => 1520, 'state_name' => 'Francisco Morazán', 'state_code' => 'FM', 'country_code' => 'HN'],
            ['id' => 1521, 'state_name' => 'Gracias a Dios', 'state_code' => 'GD', 'country_code' => 'HN'],
            ['id' => 1522, 'state_name' => 'Intibucá', 'state_code' => 'IN', 'country_code' => 'HN'],
            ['id' => 1523, 'state_name' => 'La Paz', 'state_code' => 'LP', 'country_code' => 'HN'],
            ['id' => 1524, 'state_name' => 'Lempira', 'state_code' => 'LE', 'country_code' => 'HN'],
            ['id' => 1525, 'state_name' => 'Ocotepeque', 'state_code' => 'OC', 'country_code' => 'HN'],
            ['id' => 1526, 'state_name' => 'Olancho', 'state_code' => 'OL', 'country_code' => 'HN'],
            ['id' => 1527, 'state_name' => 'Santa Bárbara', 'state_code' => 'SB', 'country_code' => 'HN'],
            ['id' => 1528, 'state_name' => 'Valle', 'state_code' => 'VA', 'country_code' => 'HN'],
            ['id' => 1529, 'state_name' => 'Yoro', 'state_code' => 'YO', 'country_code' => 'HN'],
            ['id' => 2640, 'state_name' => 'Aguascalientes', 'state_code' => 'AGU', 'country_code' => 'MX'],
            ['id' => 2641, 'state_name' => 'Baja California', 'state_code' => 'BCN', 'country_code' => 'MX'],
            ['id' => 2642, 'state_name' => 'Baja California Sur', 'state_code' => 'BCS', 'country_code' => 'MX'],
            ['id' => 2643, 'state_name' => 'Campeche', 'state_code' => 'CAM', 'country_code' => 'MX'],
            ['id' => 2644, 'state_name' => 'Chiapas', 'state_code' => 'CHP', 'country_code' => 'MX'],
            ['id' => 2645, 'state_name' => 'Chihuahua', 'state_code' => 'CHH', 'country_code' => 'MX'],
            ['id' => 2646, 'state_name' => 'Coahuila', 'state_code' => 'COA', 'country_code' => 'MX'],
            ['id' => 2647, 'state_name' => 'Colima', 'state_code' => 'COL', 'country_code' => 'MX'],
            ['id' => 2648, 'state_name' => 'Durango', 'state_code' => 'DUR', 'country_code' => 'MX'],
            ['id' => 2649, 'state_name' => 'Guanajuato', 'state_code' => 'GUA', 'country_code' => 'MX'],
            ['id' => 2650, 'state_name' => 'Guerrero', 'state_code' => 'GRO', 'country_code' => 'MX'],
            ['id' => 2651, 'state_name' => 'Hidalgo', 'state_code' => 'HID', 'country_code' => 'MX'],
            ['id' => 2652, 'state_name' => 'Jalisco', 'state_code' => 'JAL', 'country_code' => 'MX'],
            ['id' => 2653, 'state_name' => 'México', 'state_code' => 'MEX', 'country_code' => 'MX'],
            ['id' => 2654, 'state_name' => 'Mexico City', 'state_code' => 'CMX', 'country_code' => 'MX'],
            ['id' => 2655, 'state_name' => 'Michoacán', 'state_code' => 'MIC', 'country_code' => 'MX'],
            ['id' => 2656, 'state_name' => 'Morelos', 'state_code' => 'MOR', 'country_code' => 'MX'],
            ['id' => 2657, 'state_name' => 'Nayarit', 'state_code' => 'NAY', 'country_code' => 'MX'],
            ['id' => 2658, 'state_name' => 'Nuevo León', 'state_code' => 'NLE', 'country_code' => 'MX'],
            ['id' => 2659, 'state_name' => 'Oaxaca', 'state_code' => 'OAX', 'country_code' => 'MX'],
            ['id' => 2660, 'state_name' => 'Puebla', 'state_code' => 'PUE', 'country_code' => 'MX'],
            ['id' => 2661, 'state_name' => 'Querétaro', 'state_code' => 'QUE', 'country_code' => 'MX'],
            ['id' => 2662, 'state_name' => 'Quintana Roo', 'state_code' => 'ROO', 'country_code' => 'MX'],
            ['id' => 2663, 'state_name' => 'San Luis Potosí', 'state_code' => 'SLP', 'country_code' => 'MX'],
            ['id' => 2664, 'state_name' => 'Sinaloa', 'state_code' => 'SIN', 'country_code' => 'MX'],
            ['id' => 2665, 'state_name' => 'Sonora', 'state_code' => 'SON', 'country_code' => 'MX'],
            ['id' => 2666, 'state_name' => 'Tabasco', 'state_code' => 'TAB', 'country_code' => 'MX'],
            ['id' => 2667, 'state_name' => 'Tamaulipas', 'state_code' => 'TAM', 'country_code' => 'MX'],
            ['id' => 2668, 'state_name' => 'Tlaxcala', 'state_code' => 'TLA', 'country_code' => 'MX'],
            ['id' => 2669, 'state_name' => 'Veracruz', 'state_code' => 'VER', 'country_code' => 'MX'],
            ['id' => 2670, 'state_name' => 'Yucatán', 'state_code' => 'YUC', 'country_code' => 'MX'],
            ['id' => 2671, 'state_name' => 'Zacatecas', 'state_code' => 'ZAC', 'country_code' => 'MX'],
            ['id' => 2922, 'state_name' => 'Boaco', 'state_code' => 'BO', 'country_code' => 'NI'],
            ['id' => 2923, 'state_name' => 'Carazo', 'state_code' => 'CA', 'country_code' => 'NI'],
            ['id' => 2924, 'state_name' => 'Chinandega', 'state_code' => 'CI', 'country_code' => 'NI'],
            ['id' => 2925, 'state_name' => 'Chontales', 'state_code' => 'CO', 'country_code' => 'NI'],
            ['id' => 2926, 'state_name' => 'Estelí', 'state_code' => 'ES', 'country_code' => 'NI'],
            ['id' => 2927, 'state_name' => 'Granada', 'state_code' => 'GR', 'country_code' => 'NI'],
            ['id' => 2928, 'state_name' => 'Jinotega', 'state_code' => 'JI', 'country_code' => 'NI'],
            ['id' => 2929, 'state_name' => 'León', 'state_code' => 'LE', 'country_code' => 'NI'],
            ['id' => 2930, 'state_name' => 'Madriz', 'state_code' => 'MD', 'country_code' => 'NI'],
            ['id' => 2931, 'state_name' => 'Managua', 'state_code' => 'MN', 'country_code' => 'NI'],
            ['id' => 2932, 'state_name' => 'Masaya', 'state_code' => 'MS', 'country_code' => 'NI'],
            ['id' => 2933, 'state_name' => 'Matagalpa', 'state_code' => 'MT', 'country_code' => 'NI'],
            ['id' => 2934, 'state_name' => 'North Caribbean Coast Autonomous Region', 'state_code' => 'AN', 'country_code' => 'NI'],
            ['id' => 2935, 'state_name' => 'Río San Juan', 'state_code' => 'SJ', 'country_code' => 'NI'],
            ['id' => 2936, 'state_name' => 'Rivas', 'state_code' => 'RI', 'country_code' => 'NI'],
            ['id' => 2937, 'state_name' => 'South Caribbean Coast Autonomous Region', 'state_code' => 'AS', 'country_code' => 'NI'],
            ['id' => 3073, 'state_name' => 'Alto Paraguay', 'state_code' => '16', 'country_code' => 'PY'],
            ['id' => 3074, 'state_name' => 'Alto Paraná', 'state_code' => '10', 'country_code' => 'PY'],
            ['id' => 3075, 'state_name' => 'Amambay', 'state_code' => '13', 'country_code' => 'PY'],
            ['id' => 3076, 'state_name' => 'Boquerón', 'state_code' => '19', 'country_code' => 'PY'],
            ['id' => 3077, 'state_name' => 'Caaguazú', 'state_code' => '5', 'country_code' => 'PY'],
            ['id' => 3078, 'state_name' => 'Caazapá', 'state_code' => '6', 'country_code' => 'PY'],
            ['id' => 3079, 'state_name' => 'Canindeyú', 'state_code' => '14', 'country_code' => 'PY'],
            ['id' => 3080, 'state_name' => 'Central', 'state_code' => '11', 'country_code' => 'PY'],
            ['id' => 3081, 'state_name' => 'Concepción', 'state_code' => '1', 'country_code' => 'PY'],
            ['id' => 3082, 'state_name' => 'Cordillera', 'state_code' => '3', 'country_code' => 'PY'],
            ['id' => 3083, 'state_name' => 'Guairá', 'state_code' => '4', 'country_code' => 'PY'],
            ['id' => 3084, 'state_name' => 'Itapúa', 'state_code' => '7', 'country_code' => 'PY'],
            ['id' => 3085, 'state_name' => 'Misiones', 'state_code' => '8', 'country_code' => 'PY'],
            ['id' => 3086, 'state_name' => 'Ñeembucú', 'state_code' => '12', 'country_code' => 'PY'],
            ['id' => 3087, 'state_name' => 'Paraguarí', 'state_code' => '9', 'country_code' => 'PY'],
            ['id' => 3088, 'state_name' => 'Presidente Hayes', 'state_code' => '15', 'country_code' => 'PY'],
            ['id' => 3089, 'state_name' => 'San Pedro', 'state_code' => '2', 'country_code' => 'PY'],
            ['id' => 3090, 'state_name' => 'Amazonas', 'state_code' => 'AMA', 'country_code' => 'PE'],
            ['id' => 3091, 'state_name' => 'Áncash', 'state_code' => 'ANC', 'country_code' => 'PE'],
            ['id' => 3092, 'state_name' => 'Apurímac', 'state_code' => 'APU', 'country_code' => 'PE'],
            ['id' => 3093, 'state_name' => 'Arequipa', 'state_code' => 'ARE', 'country_code' => 'PE'],
            ['id' => 3094, 'state_name' => 'Ayacucho', 'state_code' => 'AYA', 'country_code' => 'PE'],
            ['id' => 3095, 'state_name' => 'Cajamarca', 'state_code' => 'CAJ', 'country_code' => 'PE'],
            ['id' => 3096, 'state_name' => 'Callao', 'state_code' => 'CAL', 'country_code' => 'PE'],
            ['id' => 3097, 'state_name' => 'Cusco', 'state_code' => 'CUS', 'country_code' => 'PE'],
            ['id' => 3098, 'state_name' => 'Huancavelica', 'state_code' => 'HUV', 'country_code' => 'PE'],
            ['id' => 3099, 'state_name' => 'Huanuco', 'state_code' => 'HUC', 'country_code' => 'PE'],
            ['id' => 3100, 'state_name' => 'Ica', 'state_code' => 'ICA', 'country_code' => 'PE'],
            ['id' => 3101, 'state_name' => 'Junín', 'state_code' => 'JUN', 'country_code' => 'PE'],
            ['id' => 3102, 'state_name' => 'La Libertad', 'state_code' => 'LAL', 'country_code' => 'PE'],
            ['id' => 3103, 'state_name' => 'Lambayeque', 'state_code' => 'LAM', 'country_code' => 'PE'],
            ['id' => 3104, 'state_name' => 'Lima', 'state_code' => 'LIM', 'country_code' => 'PE'],
            ['id' => 3105, 'state_name' => 'Madre de Dios', 'state_code' => 'MDD', 'country_code' => 'PE'],
            ['id' => 3106, 'state_name' => 'Moquegua', 'state_code' => 'MOQ', 'country_code' => 'PE'],
            ['id' => 3107, 'state_name' => 'Pasco', 'state_code' => 'PAS', 'country_code' => 'PE'],
            ['id' => 3108, 'state_name' => 'Piura', 'state_code' => 'PIU', 'country_code' => 'PE'],
            ['id' => 3109, 'state_name' => 'Puno', 'state_code' => 'PUN', 'country_code' => 'PE'],
            ['id' => 3110, 'state_name' => 'San Martín', 'state_code' => 'SAM', 'country_code' => 'PE'],
            ['id' => 3111, 'state_name' => 'Tacna', 'state_code' => 'TAC', 'country_code' => 'PE'],
            ['id' => 3112, 'state_name' => 'Tumbes', 'state_code' => 'TUM', 'country_code' => 'PE'],
            ['id' => 3113, 'state_name' => 'Ucayali', 'state_code' => 'UCA', 'country_code' => 'PE'],
            ['id' => 3790, 'state_name' => 'A Coruña', 'state_code' => 'C', 'country_code' => 'ES'],
            ['id' => 3791, 'state_name' => 'Albacete', 'state_code' => 'AB', 'country_code' => 'ES'],
            ['id' => 3792, 'state_name' => 'Alicante', 'state_code' => 'A', 'country_code' => 'ES'],
            ['id' => 3793, 'state_name' => 'Almería', 'state_code' => 'AL', 'country_code' => 'ES'],
            ['id' => 3794, 'state_name' => 'Andalusia', 'state_code' => 'AN', 'country_code' => 'ES'],
            ['id' => 3795, 'state_name' => 'Araba / Álava', 'state_code' => 'VI', 'country_code' => 'ES'],
            ['id' => 3796, 'state_name' => 'Aragon', 'state_code' => 'AR', 'country_code' => 'ES'],
            ['id' => 3797, 'state_name' => 'Badajoz', 'state_code' => 'BA', 'country_code' => 'ES'],
            ['id' => 3798, 'state_name' => 'Balearic Islands', 'state_code' => 'PM', 'country_code' => 'ES'],
            ['id' => 3799, 'state_name' => 'Barcelona', 'state_code' => 'B', 'country_code' => 'ES'],
            ['id' => 3800, 'state_name' => 'Basque Country', 'state_code' => 'PV', 'country_code' => 'ES'],
            ['id' => 3801, 'state_name' => 'Biscay', 'state_code' => 'BI', 'country_code' => 'ES'],
            ['id' => 3802, 'state_name' => 'Burgos', 'state_code' => 'BU', 'country_code' => 'ES'],
            ['id' => 3803, 'state_name' => 'Cáceres', 'state_code' => 'CC', 'country_code' => 'ES'],
            ['id' => 3804, 'state_name' => 'Cádiz', 'state_code' => 'CA', 'country_code' => 'ES'],
            ['id' => 3805, 'state_name' => 'Canary Islands', 'state_code' => 'CN', 'country_code' => 'ES'],
            ['id' => 3806, 'state_name' => 'Cantabria', 'state_code' => 'S', 'country_code' => 'ES'],
            ['id' => 3807, 'state_name' => 'Castellón', 'state_code' => 'CS', 'country_code' => 'ES'],
            ['id' => 3808, 'state_name' => 'Castile and León', 'state_code' => 'CL', 'country_code' => 'ES'],
            ['id' => 3809, 'state_name' => 'Castile-La Mancha', 'state_code' => 'CM', 'country_code' => 'ES'],
            ['id' => 3810, 'state_name' => 'Catalonia', 'state_code' => 'CT', 'country_code' => 'ES'],
            ['id' => 3811, 'state_name' => 'Ceuta', 'state_code' => 'CE', 'country_code' => 'ES'],
            ['id' => 3812, 'state_name' => 'Ciudad Real', 'state_code' => 'CR', 'country_code' => 'ES'],
            ['id' => 3813, 'state_name' => 'Community of Madrid', 'state_code' => 'MD', 'country_code' => 'ES'],
            ['id' => 3814, 'state_name' => 'Córdoba', 'state_code' => 'CO', 'country_code' => 'ES'],
            ['id' => 3815, 'state_name' => 'Cuenca', 'state_code' => 'CU', 'country_code' => 'ES'],
            ['id' => 3816, 'state_name' => 'Extremadura', 'state_code' => 'EX', 'country_code' => 'ES'],
            ['id' => 3817, 'state_name' => 'Galicia', 'state_code' => 'GA', 'country_code' => 'ES'],
            ['id' => 3818, 'state_name' => 'Gipuzkoa', 'state_code' => 'SS', 'country_code' => 'ES'],
            ['id' => 3819, 'state_name' => 'Girona', 'state_code' => 'GI', 'country_code' => 'ES'],
            ['id' => 3820, 'state_name' => 'Granada', 'state_code' => 'GR', 'country_code' => 'ES'],
            ['id' => 3821, 'state_name' => 'Guadalajara', 'state_code' => 'GU', 'country_code' => 'ES'],
            ['id' => 3822, 'state_name' => 'Huelva', 'state_code' => 'H', 'country_code' => 'ES'],
            ['id' => 3823, 'state_name' => 'Huesca', 'state_code' => 'HU', 'country_code' => 'ES'],
            ['id' => 3824, 'state_name' => 'Jaén', 'state_code' => 'J', 'country_code' => 'ES'],
            ['id' => 3825, 'state_name' => 'La Rioja', 'state_code' => 'RI', 'country_code' => 'ES'],
            ['id' => 3826, 'state_name' => 'Las Palmas', 'state_code' => 'GC', 'country_code' => 'ES'],
            ['id' => 3827, 'state_name' => 'León', 'state_code' => 'LE', 'country_code' => 'ES'],
            ['id' => 3828, 'state_name' => 'Lleida', 'state_code' => 'L', 'country_code' => 'ES'],
            ['id' => 3829, 'state_name' => 'Lugo', 'state_code' => 'LU', 'country_code' => 'ES'],
            ['id' => 3830, 'state_name' => 'Madrid', 'state_code' => 'M', 'country_code' => 'ES'],
            ['id' => 3831, 'state_name' => 'Málaga', 'state_code' => 'MA', 'country_code' => 'ES'],
            ['id' => 3832, 'state_name' => 'Melilla', 'state_code' => 'ML', 'country_code' => 'ES'],
            ['id' => 3833, 'state_name' => 'Murcia', 'state_code' => 'MU', 'country_code' => 'ES'],
            ['id' => 3834, 'state_name' => 'Navarre', 'state_code' => 'NC', 'country_code' => 'ES'],
            ['id' => 3835, 'state_name' => 'Ourense', 'state_code' => 'OR', 'country_code' => 'ES'],
            ['id' => 3836, 'state_name' => 'Palencia', 'state_code' => 'P', 'country_code' => 'ES'],
            ['id' => 3837, 'state_name' => 'Pontevedra', 'state_code' => 'PO', 'country_code' => 'ES'],
            ['id' => 3838, 'state_name' => 'Province of Asturias', 'state_code' => 'O', 'country_code' => 'ES'],
            ['id' => 3839, 'state_name' => 'Province of Ávila', 'state_code' => 'AV', 'country_code' => 'ES'],
            ['id' => 3840, 'state_name' => 'Region of Murcia', 'state_code' => 'MC', 'country_code' => 'ES'],
            ['id' => 3841, 'state_name' => 'Salamanca', 'state_code' => 'SA', 'country_code' => 'ES'],
            ['id' => 3842, 'state_name' => 'Santa Cruz de Tenerife', 'state_code' => 'TF', 'country_code' => 'ES'],
            ['id' => 3843, 'state_name' => 'Segovia', 'state_code' => 'SG', 'country_code' => 'ES'],
            ['id' => 3844, 'state_name' => 'Seville', 'state_code' => 'SE', 'country_code' => 'ES'],
            ['id' => 3845, 'state_name' => 'Soria', 'state_code' => 'SO', 'country_code' => 'ES'],
            ['id' => 3846, 'state_name' => 'Tarragona', 'state_code' => 'T', 'country_code' => 'ES'],
            ['id' => 3847, 'state_name' => 'Teruel', 'state_code' => 'TE', 'country_code' => 'ES'],
            ['id' => 3848, 'state_name' => 'Toledo', 'state_code' => 'TO', 'country_code' => 'ES'],
            ['id' => 3849, 'state_name' => 'Valencia', 'state_code' => 'V', 'country_code' => 'ES'],
            ['id' => 3850, 'state_name' => 'Valencian Community', 'state_code' => 'VC', 'country_code' => 'ES'],
            ['id' => 3851, 'state_name' => 'Valladolid', 'state_code' => 'VA', 'country_code' => 'ES'],
            ['id' => 3852, 'state_name' => 'Zamora', 'state_code' => 'ZA', 'country_code' => 'ES'],
            ['id' => 3853, 'state_name' => 'Zaragoza', 'state_code' => 'Z', 'country_code' => 'ES'],
            ['id' => 4659, 'state_name' => 'Alabama', 'state_code' => 'AL', 'country_code' => 'US'],
            ['id' => 4660, 'state_name' => 'Alaska', 'state_code' => 'AK', 'country_code' => 'US'],
            ['id' => 4661, 'state_name' => 'American Samoa', 'state_code' => 'AS', 'country_code' => 'US'],
            ['id' => 4662, 'state_name' => 'Arizona', 'state_code' => 'AZ', 'country_code' => 'US'],
            ['id' => 4663, 'state_name' => 'Arkansas', 'state_code' => 'AR', 'country_code' => 'US'],
            ['id' => 4664, 'state_name' => 'Baker Island', 'state_code' => 'UM-81', 'country_code' => 'US'],
            ['id' => 4665, 'state_name' => 'California', 'state_code' => 'CA', 'country_code' => 'US'],
            ['id' => 4666, 'state_name' => 'Colorado', 'state_code' => 'CO', 'country_code' => 'US'],
            ['id' => 4667, 'state_name' => 'Connecticut', 'state_code' => 'CT', 'country_code' => 'US'],
            ['id' => 4668, 'state_name' => 'Delaware', 'state_code' => 'DE', 'country_code' => 'US'],
            ['id' => 4669, 'state_name' => 'District of Columbia', 'state_code' => 'DC', 'country_code' => 'US'],
            ['id' => 4670, 'state_name' => 'Florida', 'state_code' => 'FL', 'country_code' => 'US'],
            ['id' => 4671, 'state_name' => 'Georgia', 'state_code' => 'GA', 'country_code' => 'US'],
            ['id' => 4672, 'state_name' => 'Guam', 'state_code' => 'GU', 'country_code' => 'US'],
            ['id' => 4673, 'state_name' => 'Hawaii', 'state_code' => 'HI', 'country_code' => 'US'],
            ['id' => 4674, 'state_name' => 'Howland Island', 'state_code' => 'UM-84', 'country_code' => 'US'],
            ['id' => 4675, 'state_name' => 'Idaho', 'state_code' => 'ID', 'country_code' => 'US'],
            ['id' => 4676, 'state_name' => 'Illinois', 'state_code' => 'IL', 'country_code' => 'US'],
            ['id' => 4677, 'state_name' => 'Indiana', 'state_code' => 'IN', 'country_code' => 'US'],
            ['id' => 4678, 'state_name' => 'Iowa', 'state_code' => 'IA', 'country_code' => 'US'],
            ['id' => 4679, 'state_name' => 'Jarvis Island', 'state_code' => 'UM-86', 'country_code' => 'US'],
            ['id' => 4680, 'state_name' => 'Johnston Atoll', 'state_code' => 'UM-67', 'country_code' => 'US'],
            ['id' => 4681, 'state_name' => 'Kansas', 'state_code' => 'KS', 'country_code' => 'US'],
            ['id' => 4682, 'state_name' => 'Kentucky', 'state_code' => 'KY', 'country_code' => 'US'],
            ['id' => 4683, 'state_name' => 'Kingman Reef', 'state_code' => 'UM-89', 'country_code' => 'US'],
            ['id' => 4684, 'state_name' => 'Louisiana', 'state_code' => 'LA', 'country_code' => 'US'],
            ['id' => 4685, 'state_name' => 'Maine', 'state_code' => 'ME', 'country_code' => 'US'],
            ['id' => 4686, 'state_name' => 'Maryland', 'state_code' => 'MD', 'country_code' => 'US'],
            ['id' => 4687, 'state_name' => 'Massachusetts', 'state_code' => 'MA', 'country_code' => 'US'],
            ['id' => 4688, 'state_name' => 'Michigan', 'state_code' => 'MI', 'country_code' => 'US'],
            ['id' => 4689, 'state_name' => 'Midway Atoll', 'state_code' => 'UM-71', 'country_code' => 'US'],
            ['id' => 4690, 'state_name' => 'Minnesota', 'state_code' => 'MN', 'country_code' => 'US'],
            ['id' => 4691, 'state_name' => 'Mississippi', 'state_code' => 'MS', 'country_code' => 'US'],
            ['id' => 4692, 'state_name' => 'Missouri', 'state_code' => 'MO', 'country_code' => 'US'],
            ['id' => 4693, 'state_name' => 'Montana', 'state_code' => 'MT', 'country_code' => 'US'],
            ['id' => 4694, 'state_name' => 'Navassa Island', 'state_code' => 'UM-76', 'country_code' => 'US'],
            ['id' => 4695, 'state_name' => 'Nebraska', 'state_code' => 'NE', 'country_code' => 'US'],
            ['id' => 4696, 'state_name' => 'Nevada', 'state_code' => 'NV', 'country_code' => 'US'],
            ['id' => 4697, 'state_name' => 'New Hampshire', 'state_code' => 'NH', 'country_code' => 'US'],
            ['id' => 4698, 'state_name' => 'New Jersey', 'state_code' => 'NJ', 'country_code' => 'US'],
            ['id' => 4699, 'state_name' => 'New Mexico', 'state_code' => 'NM', 'country_code' => 'US'],
            ['id' => 4700, 'state_name' => 'New York', 'state_code' => 'NY', 'country_code' => 'US'],
            ['id' => 4701, 'state_name' => 'North Carolina', 'state_code' => 'NC', 'country_code' => 'US'],
            ['id' => 4702, 'state_name' => 'North Dakota', 'state_code' => 'ND', 'country_code' => 'US'],
            ['id' => 4703, 'state_name' => 'Northern Mariana Islands', 'state_code' => 'MP', 'country_code' => 'US'],
            ['id' => 4704, 'state_name' => 'Ohio', 'state_code' => 'OH', 'country_code' => 'US'],
            ['id' => 4705, 'state_name' => 'Oklahoma', 'state_code' => 'OK', 'country_code' => 'US'],
            ['id' => 4706, 'state_name' => 'Oregon', 'state_code' => 'OR', 'country_code' => 'US'],
            ['id' => 4707, 'state_name' => 'Palmyra Atoll', 'state_code' => 'UM-95', 'country_code' => 'US'],
            ['id' => 4708, 'state_name' => 'Pennsylvania', 'state_code' => 'PA', 'country_code' => 'US'],
            ['id' => 4709, 'state_name' => 'Puerto Rico', 'state_code' => 'PR', 'country_code' => 'US'],
            ['id' => 4710, 'state_name' => 'Rhode Island', 'state_code' => 'RI', 'country_code' => 'US'],
            ['id' => 4711, 'state_name' => 'South Carolina', 'state_code' => 'SC', 'country_code' => 'US'],
            ['id' => 4712, 'state_name' => 'South Dakota', 'state_code' => 'SD', 'country_code' => 'US'],
            ['id' => 4713, 'state_name' => 'Tennessee', 'state_code' => 'TN', 'country_code' => 'US'],
            ['id' => 4714, 'state_name' => 'Texas', 'state_code' => 'TX', 'country_code' => 'US'],
            ['id' => 4715, 'state_name' => 'United States Minor Outlying Islands', 'state_code' => 'UM', 'country_code' => 'US'],
            ['id' => 4716, 'state_name' => 'United States Virgin Islands', 'state_code' => 'VI', 'country_code' => 'US'],
            ['id' => 4717, 'state_name' => 'Utah', 'state_code' => 'UT', 'country_code' => 'US'],
            ['id' => 4718, 'state_name' => 'Vermont', 'state_code' => 'VT', 'country_code' => 'US'],
            ['id' => 4719, 'state_name' => 'Virginia', 'state_code' => 'VA', 'country_code' => 'US'],
            ['id' => 4720, 'state_name' => 'Wake Island', 'state_code' => 'UM-79', 'country_code' => 'US'],
            ['id' => 4721, 'state_name' => 'Washington', 'state_code' => 'WA', 'country_code' => 'US'],
            ['id' => 4722, 'state_name' => 'West Virginia', 'state_code' => 'WV', 'country_code' => 'US'],
            ['id' => 4723, 'state_name' => 'Wisconsin', 'state_code' => 'WI', 'country_code' => 'US'],
            ['id' => 4724, 'state_name' => 'Wyoming', 'state_code' => 'WY', 'country_code' => 'US'],
            ['id' => 4725, 'state_name' => 'Artigas', 'state_code' => 'AR', 'country_code' => 'UY'],
            ['id' => 4726, 'state_name' => 'Canelones', 'state_code' => 'CA', 'country_code' => 'UY'],
            ['id' => 4727, 'state_name' => 'Cerro Largo', 'state_code' => 'CL', 'country_code' => 'UY'],
            ['id' => 4728, 'state_name' => 'Colonia', 'state_code' => 'CO', 'country_code' => 'UY'],
            ['id' => 4729, 'state_name' => 'Durazno', 'state_code' => 'DU', 'country_code' => 'UY'],
            ['id' => 4730, 'state_name' => 'Flores', 'state_code' => 'FS', 'country_code' => 'UY'],
            ['id' => 4731, 'state_name' => 'Florida', 'state_code' => 'FD', 'country_code' => 'UY'],
            ['id' => 4732, 'state_name' => 'Lavalleja', 'state_code' => 'LA', 'country_code' => 'UY'],
            ['id' => 4733, 'state_name' => 'Maldonado', 'state_code' => 'MA', 'country_code' => 'UY'],
            ['id' => 4734, 'state_name' => 'Montevideo', 'state_code' => 'MO', 'country_code' => 'UY'],
            ['id' => 4735, 'state_name' => 'Paysandú', 'state_code' => 'PA', 'country_code' => 'UY'],
            ['id' => 4736, 'state_name' => 'Río Negro', 'state_code' => 'RN', 'country_code' => 'UY'],
            ['id' => 4737, 'state_name' => 'Rivera', 'state_code' => 'RV', 'country_code' => 'UY'],
            ['id' => 4738, 'state_name' => 'Rocha', 'state_code' => 'RO', 'country_code' => 'UY'],
            ['id' => 4739, 'state_name' => 'Salto', 'state_code' => 'SA', 'country_code' => 'UY'],
            ['id' => 4740, 'state_name' => 'San José', 'state_code' => 'SJ', 'country_code' => 'UY'],
            ['id' => 4741, 'state_name' => 'Soriano', 'state_code' => 'SO', 'country_code' => 'UY'],
            ['id' => 4742, 'state_name' => 'Tacuarembó', 'state_code' => 'TA', 'country_code' => 'UY'],
            ['id' => 4743, 'state_name' => 'Treinta y Tres', 'state_code' => 'TT', 'country_code' => 'UY']
        ]);

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('country_divisions');
    }
};
